options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/ksahamzala-sb-hamzalab/testnodejsser/my-app:${SHORT_SHA}'
      - '.'

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/ksahamzala-sb-hamzalab/testnodejsser/my-app:${SHORT_SHA}'

images:
  - 'us-central1-docker.pkg.dev/ksahamzala-sb-hamzalab/testnodejsser/my-app:${SHORT_SHA}'
