options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/ksahamzala-sb-hamzalab/testnodejsser/my-app:${SHORT_SHA}'
      - '.'

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/ksahamzala-sb-hamzalab/testnodejsser/my-app:${SHORT_SHA}'

  # Push to cloud run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/ksahamzala-sb-hamzalab/testnodejsser/my-app:${SHORT_SHA}'
      - '--region'
      - 'me-west1'
    

images:
  - 'us-central1-docker.pkg.dev/ksahamzala-sb-hamzalab/testnodejsser/my-app:${SHORT_SHA}'
